workers_dev = true
name = "my-react-router-worker"
compatibility_date = "2025-03-11"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
